### ISSUE TITLE
.xcodeproj variant?

### ISSUE THREAD

**Issue by Kush-S-Patel** [tkoehlerlg/SwiftUIWPArticleLoader#1]
Hello there,

Thank you so much for making this, this is exactly what I was looking for! 

I just wanted to ask whether you could provide a working iOS .xcodeproj version so I can get a test build working on my simulator? I hope to analyze some of the JSON elements of your code, and testing different versions by editing how JSON is parsed.

Please let me know, thank you again so much for making this!

**Comment by tkoehlerlg** [comment]
Hey @thebrokenace,

Thank you for your kind words. ☺️

The features are in work, Version 1.3.0 will provide a **Demo Project** and _more accessibility_ to **Contentful Data**. If you need any more features please write me. 😁

Torben

**Comment by tkoehlerlg** [comment]
Hey @thebrokenace,

Version **1.3.0** is now online. All the features in you're request are now inbuilt.

Torben
