### ISSUE TITLE
How to use ImageLoader?

### ISSUE THREAD

**Issue by Kush-S-Patel** [tkoehlerlg/SwiftUIWPArticleLoader#2]
Hey, thanks so much for the .xcodeproj file! It has helped loads, I'm able to understand how to use the API in much better detail now. :)

Just a quick question, I'm using your project with my app, I was wondering how to load images in a WP article onto the SwiftUI page? For article.content only image URLs are loaded rather than actual images. Also, how can I load "article.featuredImageLoader.image"? It seems to always unwrap a nil no matter what I try, and my articles have a featured image.

Thanks for any help, and thanks so much for making this project, it's incredibly helpful!!

**Comment by tkoehlerlg** [comment]
Hey @thebrokenace,

You can now find a description for the ImageLoader in the README of **Version 1.3.1**. :)

Torben

**Comment by Kush-S-Patel** [comment]
Thanks so much for the swift response!! Just a quick question, the API seems to be at iOS 14 minimum, my application is iOS 13 native, is there any way to include backwards compatibility? Thanks again for all the help, I really appreciate it!

**Comment by tkoehlerlg** [comment]
Hey @thebrokenace,
 
The package is now compatible with **iOS 13**, but please be aware that **_AsyncImage is only for iOS 14_** because I use _State Objects_ to update our view when the image is loaded.

Torben

**Comment by Kush-S-Patel** [comment]
Thank you so much Torben!! Just a quick bug I found, article.title seems to yield the article content rather than the title. Attached is a screenshot:
<img width="362" alt="Screen Shot 2021-08-07 at 10 34 42 PM" src="https://user-images.githubusercontent.com/77700122/128621988-451a2048-27d4-41c9-aa8f-4724cee4e786.png">

**Comment by tkoehlerlg** [comment]
Hey @thebrokenace,

Thank you for your hint, I've found and fixed the Bug.

Torben
